### ISSUE TITLE
how to start qwerty

### ISSUE THREAD

**Issue by co-dh** [narke/colorForth#3]
In the color.asm, it said Peter Appelman ported with qwerty mods, but I'm not able to find out how to turn on the querty keyboard, can you help?

**Comment by narke** [comment]
AFAIK in the old release there was no qwerty mode ported from what Peter Appelman did, and I don't know where his colorForth is. But there was a release 10 years ago by Mark Tillotson, who handled qwerty mode (I have it somewhere if you want). And more importantly the new release made by Howerd Oakford seems to have a qwerty mode, I never used it but if you want you must type: space then a new entry mode will be displayed and type "qwert". Personally I didn't get far in that mode.

**Comment by co-dh** [comment]
thank you, I ended up with implemented colemak on the standard colorforth
